[package]
name = "maple-server"
version = "0.1.0"
edition = "2021"
rust-version = "1.77"

[[bin]]
name = "maple-server"
path = "src/main.rs"

[dependencies]
maple-core = { path = "../maple-core" }
maple-crypto = { path = "../maple-crypto" }
# maple-wz = { path = "../maple-wz" }
# maple-db = { path = "../maple-db" }
# maple-net = { path = "../maple-net" }
# maple-game = { path = "../maple-game" }
# maple-script = { path = "../maple-script" }
# tokio = { version = "1", features = ["full"] }
# tracing = "0.1"
# tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
# toml = "0.8"
