[package]
name = "maple-game"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
maple-core = { path = "../maple-core" }
maple-db = { path = "../maple-db" }
maple-net = { path = "../maple-net" }
maple-script = { path = "../maple-script" }
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
